# Generated by Django 4.1.7 on 2023-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('CONNECT', 'CONNECT'), ('DELETE', 'DELETE'), ('GET', 'GET'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('POST', 'POST'), ('PUT', 'PUT')], max_length=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
